# Generated by Django 4.1 on 2023-03-04 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_ID', models.IntegerField(default=0, max_length=999999)),
                ('name', models.CharField(default='', max_length=150)),
                ('cnic', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=50)),
                ('licnese', models.CharField(default='', max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('cnic', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=12)),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_code', models.CharField(default='', max_length=10)),
                ('route', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_code', models.CharField(default='', max_length=10)),
                ('schedule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default='', max_length=100)),
                ('fare', models.IntegerField()),
                ('availables', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(default='', max_length=150)),
                ('boarding_point', models.CharField(default='', max_length=150)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ticket')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Buse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_code', models.CharField(default='', max_length=10)),
                ('type', models.CharField(default='', max_length=150)),
                ('capacity', models.IntegerField(default=0, max_length=150)),
                ('bus_no', models.CharField(default='', max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('route', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.route')),
                ('schedule', models.ManyToManyField(to='main.schedule')),
            ],
        ),
    ]
