# Generated by Django 4.1 on 2023-03-04 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_buse_capacity_alter_driver_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buse',
            name='driver',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
        ),
    ]
