# Generated by Django 4.1 on 2023-03-04 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_buse_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buse',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.driver'),
        ),
    ]
