# Generated by Django 4.1 on 2023-03-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bus_type_carousel_route_fare_route_bus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buse',
            name='type',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.bus_type'),
        ),
    ]
