# Generated by Django 4.1 on 2023-03-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_buse_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus_type',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fare',
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField()),
                ('Schedule', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
                ('bus_type', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.bus_type')),
                ('route', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.route')),
            ],
        ),
    ]
