# Generated by Django 4.1 on 2023-03-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_route_bus_type_remove_route_fare_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
