# Generated by Django 4.1 on 2023-03-05 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0009_contact_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(default='', max_length=60)),
                ('first_name', models.CharField(default='', max_length=60)),
                ('last_name', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(max_length=40, null=True)),
                ('gender', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
